---
- name: sample book
  hosts: ansible_client
  remote_user: root
  become: true
  tasks:
  - name: Cai dat LAMP
    yum:
      name: ['httpd', 'mariadb-server', 'mariadb', 'php', 'php-mysql', 'php-fpm']
      state: present
  - name: run httpd
    service:
        name: httpd
        state: started
  - name: create content
    copy:
        content: "Kiem tra ket noi toi instance"
        dest: /var/www/html/index.html
  
  - name: dam bao service da duoc enable va chay
    service:
        name: "{{item}}"
        state: started
        enabled: True
    with_items:
    - mariadb
    - httpd

  - name: Cai firewalld
    yum:
      name: firewalld
      state: latest
    #notify:
    #  - start firewalld
  
  - name: start firewalld
    service: 
      name: firewalld 
      state: started
      enabled: yes

  - name: Cho phep HTTP va HTTPS di qua duoc Firewall
    firewalld:
      service: "{{item}}"
      state: enabled
      permanent: True
      immediate: True
    become: True
    with_items:
    - http
    - https

  #handlers:
  #  - name: start firewalld
  #    service: 
  #      name: firewalld
  #      state: started