---
- name: sample book
  hosts: ansible_client
  remote_user: root
  become: true
  tasks:
  # update all packages
  - name: Update Packages
    yum:
      name: '*'
      state: latest

  # Add repo    
  - name: Add repo MariaDB
    yum_repository:
      name: mariadb
      description: MariaDB Repo
      file: mariadb
      gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
      baseurl: http://yum.mariadb.org/10.4.18/rhel7-amd64/
      gpgcheck: 1

  - name: Add repo Nginx
    yum_repository:
      name: nginx-stable
      description: nginx stable repo
      file: nginx
      gpgkey: https://nginx.org/keys/nginx_signing.key
      baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
      gpgcheck: 1
      enabled: yes

  # Install MariaDB, Nginx
  - name: Install Mariadb, Nginx
    yum:
      name: "{{ item }}"
      update_cache: yes
      state: latest
    loop: [ 'nginx', 'MariaDB-server', 'MariaDB-client' ]

  # Install Php
  - copy:
      src: ./scripts/php_install.sh
      dest: /root/php_install.sh
      owner: root
      group: root
      mode: 0755

  # Install Php
  - name: Install Php and Php Extensions
    command: sh /root/php_install.sh
  
  # Copy source from local host to remote AWS instance
  - copy:
      src: ../wordpress-source/
      dest: /root/remote-wordpress-source
      owner: root
      group: root
      mode: 0755

  - name: Start services
    service:
        name: "{{item}}"
        state: started
        enabled: True
    with_items:
    - mariadb
    - nginx
 

  #######################################18/04/2021

  - name: "create www directory"
    file:
      path: /var/www/example_website
      state: directory
      mode: '0775'
      owner: "centos"
      group: "centos"

  - name: delete default nginx site
    file:
      path: /etc/nginx/conf.d/default.conf
      state: absent
    notify: restart nginx

  - name: copy nginx site.conf
    template:
      src: nginx/site.conf.j2
      dest: /etc/nginx/conf.d/default.conf
      owner: root
      group: root
      mode: '0644'
    notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted


  #######################################


